// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZfMEgM1meLWoA2NisykFI1s-WlrioRQk',
    appId: '1:761344243534:web:0fc6370b71da0365e2101f',
    messagingSenderId: '761344243534',
    projectId: 'loja-flutter-f8b82',
    authDomain: 'loja-flutter-f8b82.firebaseapp.com',
    storageBucket: 'loja-flutter-f8b82.firebasestorage.app',
    measurementId: 'G-1E6SL07QN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKcdQJTKnNtE5aKqpU_Xe8FtThFt2RDNQ',
    appId: '1:761344243534:android:aa6c8e54d6e1d032e2101f',
    messagingSenderId: '761344243534',
    projectId: 'loja-flutter-f8b82',
    storageBucket: 'loja-flutter-f8b82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7KIvH_Jzg0b9dRhhqlMt5-YMV_uQNbY8',
    appId: '1:761344243534:ios:bddc9c01180b6710e2101f',
    messagingSenderId: '761344243534',
    projectId: 'loja-flutter-f8b82',
    storageBucket: 'loja-flutter-f8b82.firebasestorage.app',
    iosBundleId: 'com.example.appTestesUnitarios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7KIvH_Jzg0b9dRhhqlMt5-YMV_uQNbY8',
    appId: '1:761344243534:ios:bddc9c01180b6710e2101f',
    messagingSenderId: '761344243534',
    projectId: 'loja-flutter-f8b82',
    storageBucket: 'loja-flutter-f8b82.firebasestorage.app',
    iosBundleId: 'com.example.appTestesUnitarios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZfMEgM1meLWoA2NisykFI1s-WlrioRQk',
    appId: '1:761344243534:web:0bbda5f35ade631ee2101f',
    messagingSenderId: '761344243534',
    projectId: 'loja-flutter-f8b82',
    authDomain: 'loja-flutter-f8b82.firebaseapp.com',
    storageBucket: 'loja-flutter-f8b82.firebasestorage.app',
    measurementId: 'G-6JZJ65DSC5',
  );
}
